REVOKE CREATE ON SCHEMA audit FROM PUBLIC;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA audit FROM PUBLIC;
GRANT SELECT ON ALL TABLES IN SCHEMA audit TO PUBLIC;
REVOKE CREATE ON SCHEMA fe FROM PUBLIC;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA fe FROM PUBLIC;

REVOKE CREATE ON SCHEMA audit FROM fe;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA audit FROM fe;
GRANT USAGE ON SCHEMA audit TO fe;
GRANT INSERT ON ALL TABLES IN SCHEMA audit TO fe;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA audit TO fe;
REVOKE CREATE ON SCHEMA fe FROM fe;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA fe FROM fe;
GRANT USAGE ON SCHEMA fe TO fe;
GRANT INSERT, SELECT, UPDATE, DELETE ON ALL TABLES IN SCHEMA fe TO fe;
